// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svgiplyjhtsqjeihemfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Z2lwbHlqaHRzcWplaWhlbWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MDEzNjYsImV4cCI6MjA1MjE3NzM2Nn0.8TUsyOACeoIVRxgj_ZuUaufXbze4NJHq8IRhJwqsQF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);